spring:
  datasource:
    username: user
    url: jdbc:h2:file:./data/animedownlaoder
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

app:
  gogoanime:
    url: https://gogoanime.sk
  scheduler:
    enabled: true
    download:
      initialDelayMs: 0
      #      fixedDelayMs: 10000
      fixedDelayMs: 60000
    clean:
      numberOfDaysAfterToClean: 3
      initialDelayDays: 0
      fixedDelayDays: 1
  screenshot:
    path: \src\main\resources\screenshots\
    file-extension: jpg
