spring:
  datasource:
    username: user
    url: jdbc:h2:file:./data/animedownlaoder
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

app:
  supported-servers: Mp4UploadPage, StreamSbPage
  #  supported-servers: Mp4UploadPage, StreamSbPage, XStreamCdnPage
  #   sometimes there are problems when downloading from XStreamCdn
  gogoanime:
    url: https://gogoanime.cl
  scheduler:
    enabled: true
    download:
      initial-delay-ms: 60000
      #      fixed-delay-ms: 10000
      fixed-delay-ms: 60000
    reset:
      number-of-days-after-to-reset: 3
      initial-delay-days: 0
      fixed-delay-days: 1
    failed:
      initial-delay-minutes: 0
      fixed-delay-minutes: 10
  screenshot:
    path: \src\main\resources\screenshots\
    file-extension: jpg
  consumer:
    wait-time-seconds: 20
    download-service-retry-times: 2
  csv:
    file-name: anime.csv
  default-min-file-size: 150.0
